### ISSUE TITLE
Gerber files?

### ISSUE THREAD

**Issue by ggppjj** [ploopyco/mini-trackball#2]
Hello!

Sorry if I'm being dense, I'm a bit new to getting PCBs manufactured, and to be honest wouldn't be bothering if there were a prebuilt PCB-only option on the store. I'm trying to figure out how to get the PCBs made, the instructions and my own general (if lacking) understanding tells me to upload these files to a PCB manufacturer, but I can't seem to find one that recognizes the Altium project files as-is, is there a specific manufacturer that does? 

Alternatively, would you be willing to export the Gerber files from Altium? I tried to import the project to CircuitMaker to attempt it myself, but I genuinely cannot figure out how to import the project and I can't possibly afford the full Altium suite for one low-volume order that I was hoping to make.

Thanks, sorry again if there's something I'm just not understanding here.

**Comment by timmit99** [comment]
I'll second the "PCB Only Kit" Option. I currently have the parts printing since i want them in my own colors but would love to support the project by purchasing the PCB and switches from the store.

**Comment by daniel-dsouza** [comment]
I would also love to see an option for downloading and/or purchasing the Gerber files which I could upload to Advanced Circuits or similar. Having a parts list which I could also import into Digikey would be convenient.

Or perhaps having a completely un-assembled kit with just the PCB and non-3d printed components?

**Comment by cscott** [comment]
I'd like to see the gerbers because I've got a shop-bought kit but the white silkscreen makes it impossible to see the traces.  I'd like to do some PCB modifications and it would be really helpful to be able to see where the traces are...
